### ISSUE TITLE
Text Missing for Settings

### ISSUE THREAD

**Issue by cameren2k** [PoomSmart/YouChooseQuality#3]
The YouChooseQuality menu has no text labels on latest youtube
![image](https://github.com/user-attachments/assets/8b3fdc81-4f63-4af1-84bf-597e46fb058f)

**Comment by PoomSmart** [comment]
Can't reproduce. How did you install this tweak?

**Comment by cameren2k** [comment]
> Can't reproduce. How did you install this tweak?

I have my own fork of uYouPlus found on my github account, with changes which include YouChooseQuality. This may be an A/B related to text labels that I need to look for.

**Comment by PoomSmart** [comment]
You should add bundle symlink in this folder https://github.com/qnblackcat/uYouPlus/tree/main/Bundles

**Comment by cameren2k** [comment]
oversight on my part, thank you!
